[INFO|utils.py:32] 2021-07-20 16:25:47 Writing logs at ./logs/log-20210720-09.log
[INFO|main.py:32] 2021-07-20 16:25:47 **************************Load SemEval_Restaurants_2014 Dataset
[INFO|tokenization.py:190] 2021-07-20 16:25:48 loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/kkh/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
[INFO|main.py:112] 2021-07-20 16:25:51 ============================Training Start=====================================
[INFO|main.py:113] 2021-07-20 16:25:51  Training Exampels : 95
[INFO|main.py:114] 2021-07-20 16:25:51  Batch Size : 32
[INFO|main.py:117] 2021-07-20 16:25:51 Model save path: ./model_save/20210720-01
[INFO|main.py:124] 2021-07-20 16:25:51 ====================================Train====================================
[ERROR|main.py:149] 2021-07-20 16:25:53 ERROR
Traceback (most recent call last):
  File "main.py", line 147, in <module>
    main()
  File "main.py", line 142, in main
    train(model, optimizer, trainLoader, testLoader)
  File "main.py", line 125, in train
    train_loss = train_epoch(model, trainLoader, optimizer)
  File "main.py", line 90, in train_epoch
    loss = model(input_ids, segment_ids, input_mask, label_id)
  File "/home/kkh/anaconda3/envs/ABSA/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kkh/ABSA/AEBERT.py", line 16, in forward
    sequence_output, _ = self.bert(input_ids, token_type_ids, attention_mask, output_all_encoded_layers=False)
  File "/home/kkh/anaconda3/envs/ABSA/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'output_all_encoded_layers'
